import { PollutionAlert, AlertStatus, SeverityLevel } from '../types';
import { MOCK_ALERTS } from '../mock/data';
import { fetchFromBackend } from './apiConfig';

interface BackendAlert {
  id: string;
  category: string;
  severity: string;
  title: string;
  message: string;
}

function mapBackendAlert(b: BackendAlert, index: number): PollutionAlert {
  const sev: SeverityLevel =
    b.severity === 'high' || b.severity === 'severe'
      ? 'Critical'
      : b.severity === 'moderate'
      ? 'High'
      : 'Medium';

  return {
    id: b.id || `live-alert-${index}`,
    alertCode: `ALT-${(b.id || 'HOT').slice(0, 6).toUpperCase()}`,
    severity: sev,
    sensorId: 'CAAQMS-HOTSPOT',
    sensorModel: 'AI Anomaly Detector',
    location: b.title || 'National Capital Region',
    zone: 'Regional Airshed',
    coordinates: {
      latitude: 28.6139 + (index * 0.03 - 0.05),
      longitude: 77.209 + (index * 0.04 - 0.06),
    },
    metric: 'AQI Anomaly Score',
    value: 185,
    unit: 'AQI Index',
    threshold: 150,
    aqi: 280 + index * 15,
    timestamp: 'Live Telemetry',
    status: 'New',
    probableSource: b.message || 'Regional Industrial & Vehicular Plume',
    confidenceScore: 91,
    predictionSummary: b.message,
    recommendedAction: 'Issue citizen advisory and deploy mobile smog mitigation cannons.',
    nearbySensorCount: 4,
    relatedReportIds: [],
    activityHistory: [
      {
        id: `ah-init-${index}`,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        action: 'Alert generated by AirSentinel ML Engine',
        actor: 'AI Hotspot Engine',
        note: b.message,
      },
    ],
  };
}

let cachedAlerts: PollutionAlert[] = [...MOCK_ALERTS];

export const alertsService = {
  getAlerts: async (filters?: {
    severity?: string;
    status?: string;
    zone?: string;
    search?: string;
  }): Promise<PollutionAlert[]> => {
    try {
      const data = await fetchFromBackend<{ alerts: BackendAlert[] }>('/alerts');
      if (data && Array.isArray(data.alerts) && data.alerts.length > 0) {
        const live = data.alerts.map(mapBackendAlert);
        const liveIds = new Set(live.map((a) => a.id));
        const filteredMocks = MOCK_ALERTS.filter((m) => !liveIds.has(m.id));
        cachedAlerts = [...live, ...filteredMocks];
      }
    } catch (e) {
      console.warn('Failed to fetch backend /alerts, using cache/mock:', e);
    }

    let results = [...cachedAlerts];

    if (filters?.severity && filters.severity !== 'All') {
      results = results.filter((a) => a.severity.toLowerCase() === filters.severity?.toLowerCase());
    }

    if (filters?.status && filters.status !== 'All') {
      results = results.filter((a) => a.status.toLowerCase() === filters.status?.toLowerCase());
    }

    if (filters?.zone && filters.zone !== 'All') {
      results = results.filter((a) => a.zone.toLowerCase() === filters.zone?.toLowerCase());
    }

    if (filters?.search) {
      const q = filters.search.toLowerCase();
      results = results.filter(
        (a) =>
          a.location.toLowerCase().includes(q) ||
          a.alertCode.toLowerCase().includes(q) ||
          a.sensorModel.toLowerCase().includes(q) ||
          a.probableSource.toLowerCase().includes(q)
      );
    }

    return results;
  },

  getAlertById: async (id: string): Promise<PollutionAlert | null> => {
    const found = cachedAlerts.find((a) => a.id === id);
    return found ? { ...found } : null;
  },

  updateAlertStatus: async (
    id: string,
    status: AlertStatus,
    actorName: string,
    note?: string
  ): Promise<PollutionAlert> => {
    const index = cachedAlerts.findIndex((a) => a.id === id);
    if (index === -1) throw new Error('Alert not found');

    const updated = {
      ...cachedAlerts[index],
      status,
      activityHistory: [
        ...cachedAlerts[index].activityHistory,
        {
          id: `ah-${Date.now()}`,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          action: `Status changed to ${status}`,
          actor: actorName,
          note,
        },
      ],
    };

    cachedAlerts[index] = updated;
    return updated;
  },

  assignDepartmentToAlert: async (
    alertId: string,
    departmentId: string,
    departmentName: string,
    officerName: string,
    actor: string
  ): Promise<PollutionAlert> => {
    const index = cachedAlerts.findIndex((a) => a.id === alertId);
    if (index === -1) throw new Error('Alert not found');

    const updated = {
      ...cachedAlerts[index],
      assignedDepartmentId: departmentId,
      assignedDepartmentName: departmentName,
      assignedOfficer: officerName,
      status: 'Assigned' as AlertStatus,
      activityHistory: [
        ...cachedAlerts[index].activityHistory,
        {
          id: `ah-${Date.now()}`,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          action: `Assigned to ${departmentName} (${officerName})`,
          actor,
        },
      ],
    };

    cachedAlerts[index] = updated;
    return updated;
  },
};
